# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20151223_0241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('user', 'name')]),
        ),
    ]
