# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160101_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='likes_until_refresh',
            field=models.SmallIntegerField(default=8),
        ),
    ]
