"""
Django settings for gift_finder project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
import socket

import os
import confidential

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PRODUCTION_SERVER = socket.gethostname() == "giftstr"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = confidential.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!

if PRODUCTION_SERVER:
    DEBUG = False
    ALLOWED_HOSTS = ['*',]
    CORS_ORIGIN_ALLOW_ALL = True

else: #DEVELOPMENT SERVER
    DEBUG = True
    ALLOWED_HOSTS = []
    CORS_ORIGIN_ALLOW_ALL = True




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.amazon',
    'rest_auth.registration',
    'corsheaders',
    'api',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination'
}

# If you are running Django 1.8+, specify the context processors
# as follows:
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Already defined Django-related contexts here

                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

)

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]




ROOT_URLCONF = 'gift_finder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SITE_ID = 1

if DEBUG:
    pass
    #EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

DEFAULT_FROM_EMAIL = 'staff@giftstr.com'
SERVER_EMAIL = 'staff@giftstr.com'
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.giftstr.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'staff@giftstr.com'
EMAIL_HOST_PASSWORD = confidential.EMAIL_HOST_PASSWORD


ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "http://giftstr.com/#/"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Giftstr] "




WSGI_APPLICATION = 'gift_finder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #}
    'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
            'NAME': 'giftstr',                      # Or path to database file if using sqlite3.
            # The following settings are not used with sqlite3:
            'USER': 'admin',
            'PASSWORD': confidential.DB_PASSWORD,
            'HOST': 'localhost',                      # Empty for localhost through domain sockets or           '127.0.0.1' for localhost through TCP.
            'PORT': '5432',                      # Set to empty string for default.
        }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

DEFAULT_SUGGESTIONS = ['B00OTUC5RS', 'B007RNYHYS', 'B015PTF1S6', 'B007I0HQFM', 'B00NEJ7MMI', 'B0083WJ3M8', 'B00PHJSUY2', 'B010S9N6OO', 'B00FLYWNYQ', 'B004JHYK0G', 'B00WXUWCJM', 'B00MO21WAY', 'B01617VVCQ', 'B00ARQVM5O', 'B017MD6BTQ', 'B00K69WURQ', 'B000OR2RNM', 'B01187AAQM', 'B00U78NQHO', 'B00L98V4UW', 'B016PF4H9S', 'B00IEFXDO8', 'B000CO89T8', 'B00NWXLQD2', 'B00LCYLCB4', 'B00GDQ0RMG', 'B00F3J9G1W', 'B0051XQI84', 'B000XI6O2W', 'B001NK395Y', 'B015CQ8SGE', 'B01574SORE', 'B00TSUGXKE', 'B00VY9694M', 'B00LCIYHSK', 'B00UQQ9L8K', 'B012YZDJ9M', 'B008G9B11E', 'B004XNK7AI', 'B00B4HXOHE', 'B016WZ03LM', 'B01929H1I8', 'B00VI2L3L4', 'B012A4QUX4', 'B004S8F7QM', 'B001E6F108']
NUM_NEAREST_PERSONS = 6
NUM_RANDOM_SUGGESTIONS = 2 #This is multiplied by 2 because of controlled and uncontrolled random suggestions
LIKES_UNTIL_REFRESH = 8 #This is not a strict limit. Waits until next getSuggestions call to refresh.



